# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=30)),
                ('credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_num', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('not_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('tagline', models.TextField()),
                ('day', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('co_dj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_dj', to='scheduler.BaseUser')),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.BaseUser')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Show'),
        ),
    ]
