# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_choice_day', models.CharField(max_length=7)),
                ('second_choice_day', models.CharField(max_length=7)),
                ('third_choice_day', models.CharField(max_length=7)),
                ('first_choice_time', models.TimeField()),
                ('second_choice_time', models.TimeField()),
                ('third_choice_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('tagline', models.TextField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='show',
            name='co_dj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_dj', to='scheduler.BaseUser'),
        ),
        migrations.AddField(
            model_name='show',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_dj', to='scheduler.BaseUser'),
        ),
        migrations.AddField(
            model_name='choice',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Show'),
        ),
    ]
