# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20160829_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
