# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20160922_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crediting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('crediting_reason', models.TextField()),
                ('exec_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.BaseUser')),
            ],
        ),
    ]
