# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-16 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_crediting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
