# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20160829_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='first_choice_day',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='choice',
            name='second_choice_day',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='choice',
            name='third_choice_day',
            field=models.CharField(max_length=15),
        ),
    ]
