# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20160829_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='first_choice_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='first_choice_day',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='second_choice_day',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='second_choice_time',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='third_choice_day',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='third_choice_time',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
