# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20160829_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
