# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20160829_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='co_dj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_dj', to='scheduler.BaseUser'),
        ),
    ]
