# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_show_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
