# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_auto_20160912_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.BaseUser'),
        ),
    ]
