# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20160913_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
